// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8UV1uaYTre881ppyfJloBuC0AcqBS9nc',
    appId: '1:727663850416:web:85b4b715a4f67fed879c75',
    messagingSenderId: '727663850416',
    projectId: 'akalimuproject',
    authDomain: 'akalimuproject.firebaseapp.com',
    storageBucket: 'akalimuproject.appspot.com',
    measurementId: 'G-GDYJK6Y08P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPKOtve_BCUlRiw2BYLir1f_l7yfPuR8',
    appId: '1:727663850416:android:082f79eab8aea530879c75',
    messagingSenderId: '727663850416',
    projectId: 'akalimuproject',
    storageBucket: 'akalimuproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9diWnSOGEuNXzKGmkkRYX1lO83Bn698',
    appId: '1:727663850416:ios:21effef9eeb59bb7879c75',
    messagingSenderId: '727663850416',
    projectId: 'akalimuproject',
    storageBucket: 'akalimuproject.appspot.com',
    iosClientId: '727663850416-rvcr0iai9h7ruh7mjg2ca92v5gf262e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.akalimu',
  );
}
